### ISSUE TITLE
Increasing memory usage while opening chunks

### ISSUE THREAD

**Issue by gavargas22** [micmurawski/ovds-utils#10]
I hope you don't mind posting my questions as issues...

I am interested in using this library `ovds-utils` to make an `xarray` engine for VDS so that we can use VDS directly with `xarray`.  [How to add a new backend](https://docs.xarray.dev/en/stable/internals/how-to-add-new-backend.html)

I have made a new backend for it, and it works, but I noticed that when I load subsets of the volume, I get incrementing memory usage. I believe this is because of caching, or something like that. I am opening pieces of the vds volume using xarray in chunks, for example to get a slice or a small subset. 

But it is not clear to me how to best handle doing an operation and returning the slice result without keeping all of the other chunks

How do you handle this scenario? I will make a repo for the VDS engine and post it here so you can take a look if you are interested.

**Comment by micmurawski** [comment]
Check this [test](https://github.com/micmurawski/ovds-utils/blob/be1882436e784d95171936187d4ca1d230388acb/tests/test_vds.py#L54) case.

Figure out where to put `vds.channel(0).commit()`

**Comment by micmurawski** [comment]
Also take a look on how `__getitem__` method work https://github.com/micmurawski/ovds-utils/blob/be1882436e784d95171936187d4ca1d230388acb/src/ovds_utils/vds.py#L225
