### ISSUE TITLE
Orientation of seismic cube in vds vs numpy

### ISSUE THREAD

**Issue by gavargas22** [micmurawski/ovds-utils#9]
This is probably a very basic thing that I am unable to figure out... 😆 

I noticed that the orientation of VDS is different from a normal numpy array. How do you deal with that orientation difference?

Am I correct that VDS has the `k, i, j` (or something like that) orientation whereas numpy has a `i, j, k` orientation

I built an xarray engine for vds, and I am having some trouble returning the correct orientation for xarray. Do you have any suggestions to deal with this?

**Comment by micmurawski** [comment]
When I write pages I use `min` and `max` values from openvds API `getMinMax()` then I invert indexes (`(i,j,k)` -> `(k,j,i)`) when I load data to buffer. During reading, I am not inverting anything so I can make direct comparisons between vds object and np input data arrays (`np.array_equal(data[i, 0, :], vds[i, 0, :])`). Below I attached examples for reading and writing in code.

Writing pages
[`src/ovds_utils/ovds/writing.py line 32`](https://github.com/micmurawski/ovds-utils/blob/be1882436e784d95171936187d4ca1d230388acb/src/ovds_utils/vds.py#L39)
```
        (min, max) = page.getMinMax()
        buf[:, :, :] = data[
            min[2]: max[2],
            min[1]: max[1],
            min[0]: max[0],
        ]
```

Reading
[`src/ovds_utils/vds.py line 39`](https://github.com/micmurawski/ovds-utils/blob/be1882436e784d95171936187d4ca1d230388acb/src/ovds_utils/ovds/writing.py#L31)
```
        page = self.accesor.readPage(self.number)
        buf = np.array(page.getBuffer(), copy=False, dtype=dtype)
        return buf.__getitem__(key)
```

**Comment by gavargas22** [comment]
I see, very good thank you!
